"""
output.py — YAML and CSV writer for ats_finder results.

Writes:
  1. companies_found.yaml — directly appendable to jobradar's companies.yaml
  2. ats_report.csv       — full per-company probe report
"""

from __future__ import annotations

import csv
import io
import logging
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

# ATS platforms that produce standard slug-based entries in YAML.
# Workday is intentionally excluded here — it gets its own structured block below.
_STANDARD_ATS = {
    "greenhouse",
    "lever",
    "ashby",
    "workable",
    "smartrecruiters",
    "rippling",
    "bamboohr",
    "recruitee",
    "personio",
}


CSV_COLUMNS = [
    "company_name",
    "detected_ats",
    "slug_used",
    "jobs_found",
    "careers_url",
    "probe_time_ms",
    "status",
]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _group_by_ats(results: list[dict]) -> dict[str, list[dict]]:
    """Group found results by ATS name."""
    grouped: dict[str, list[dict]] = {}
    for r in results:
        if r.get("status") != "found":
            continue
        ats = r.get("ats")
        if not ats:
            continue
        grouped.setdefault(ats, []).append(r)
    return grouped


def _yaml_header(total_found: int, ats_breakdown: dict[str, int]) -> str:
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    lines = [
        f"# Auto-generated by ats_finder — {ts}",
        f"# Found {total_found} companies across {len(ats_breakdown)} ATS platforms",
        "#",
    ]
    for ats, count in sorted(ats_breakdown.items(), key=lambda x: -x[1]):
        lines.append(f"#   {ats}: {count}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# YAML writer
# ---------------------------------------------------------------------------

def build_yaml_block(
    all_results: list[dict],
    company_names: dict[str, str],  # slug -> original company name
) -> str:
    """
    Build a YAML string that is directly appendable to jobradar's companies.yaml.

    company_names: mapping from slug -> original company name (for the `name:` field).

    Standard ATS platforms produce entries with `slug` + `name` fields.
    Workday produces a separate block with `tenant`, `server`, `site`, and `name`
    fields — because jobradar's companies.yaml schema for Workday differs from the
    flat slug-based schema used by every other ATS.
    """
    grouped = _group_by_ats(all_results)

    total_found = sum(len(v) for v in grouped.values())
    ats_breakdown = {ats: len(v) for ats, v in grouped.items()}

    buf = io.StringIO()
    buf.write(_yaml_header(total_found, ats_breakdown))
    buf.write("\n")

    # Standard ATS entries (slug + name)
    for ats in _STANDARD_ATS:
        entries = grouped.get(ats)
        if not entries:
            continue
        buf.write(f"{ats}:\n")
        for entry in entries:
            slug = entry["slug"]
            name = company_names.get(slug, slug)
            buf.write(f"  - slug: {slug}\n")
            buf.write(f"    name: {name}\n")
        buf.write("\n")

    # Workday block — structured with tenant / server / site / name
    workday_entries = grouped.get("workday")
    if workday_entries:
        buf.write("workday:\n")
        for entry in workday_entries:
            tenant    = entry.get("tenant", "")
            wd_server = entry.get("wd_server", "")
            site      = entry.get("site", "")
            # Derive display name: prefer company_names lookup via composite slug key,
            # then fall back to the 'company' field stored on the result dict itself.
            composite_slug = entry.get("slug", "")
            name = (
                company_names.get(composite_slug)
                or entry.get("company", composite_slug)
            )
            buf.write(f"  - tenant: {tenant}\n")
            buf.write(f"    server: {wd_server}\n")
            buf.write(f"    site: {site}\n")
            buf.write(f"    name: {name}\n")
        buf.write("\n")

    return buf.getvalue()


def write_yaml(
    path: str | Path,
    all_results: list[dict],
    company_names: dict[str, str],
) -> None:
    """Write the YAML output file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    content = build_yaml_block(all_results, company_names)
    path.write_text(content, encoding="utf-8")
    logger.info("YAML written to %s", path)


# ---------------------------------------------------------------------------
# CSV writer
# ---------------------------------------------------------------------------

def build_csv_rows(
    all_results: list[dict],  # list of {company, ats, slug, jobs_found, ...}
) -> list[dict]:
    rows = []
    for r in all_results:
        rows.append({
            "company_name":   r.get("company", ""),
            "detected_ats":   r.get("ats") or "",
            "slug_used":      r.get("slug") or "",
            "jobs_found":     r.get("jobs_found", 0),
            "careers_url":    r.get("careers_url", ""),
            "probe_time_ms":  r.get("probe_time_ms", 0),
            "status":         r.get("status", "not_found"),
        })
    return rows


def write_csv(
    path: str | Path,
    all_results: list[dict],
    mode: str = "w",
) -> None:
    """Write (or append to) the CSV report file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = build_csv_rows(all_results)

    write_header = mode == "w" or not path.exists() or path.stat().st_size == 0

    with path.open(mode, newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=CSV_COLUMNS)
        if write_header:
            writer.writeheader()
        writer.writerows(rows)

    logger.info("CSV written to %s (%d rows)", path, len(rows))


# ---------------------------------------------------------------------------
# Incremental checkpoint writer
# ---------------------------------------------------------------------------

def checkpoint(
    yaml_path: str | Path,
    csv_path: str | Path,
    batch: list[dict],
    company_names: dict[str, str],
    first_batch: bool = False,
) -> None:
    """
    Write a partial batch to disk.
    YAML is rewritten each time (small file).
    CSV is appended (header written only on first batch).
    """
    write_yaml(yaml_path, batch, company_names)
    write_csv(csv_path, batch, mode="w" if first_batch else "a")


# ---------------------------------------------------------------------------
# Summary printer
# ---------------------------------------------------------------------------

def print_summary(all_results: list[dict]) -> None:
    found = [r for r in all_results if r.get("status") == "found"]
    not_found = [r for r in all_results if r.get("status") == "not_found"]
    errors = [r for r in all_results if r.get("status") == "error"]

    ats_counts: dict[str, int] = {}
    for r in found:
        ats = r.get("ats")
        if ats:
            ats_counts[ats] = ats_counts.get(ats, 0) + 1

    print("\nResults:")
    print(f"  ✅ Found:      {len(found)} companies")
    print(f"  ❌ Not found:  {len(not_found)} companies")
    print(f"  ⚠️  Errors:     {len(errors)} companies (see CSV report)")

    if ats_counts:
        print("\nATS breakdown:")
        for ats, count in sorted(ats_counts.items(), key=lambda x: -x[1]):
            print(f"  {ats.capitalize():<18} {count}")
